#!/usr/bin/env bash

set -e

echo "Generating Releng Email"

version=$(< pxf_open_source_license_file/version)

cat > pxf_artifacts/email_subject.txt << EOF
PXF Release ${version} is ready to be published to VMware Tanzu Network
EOF

cat > pxf_artifacts/email_body.txt << EOF
Hi GPDB Releng Team,

The new PXF release ${version} is ready to be published to VMware Tanzu Network.

We have uploaded the following artifacts to the appropriate RelEng release buckets:
$(ls pxf_artifacts/pxf-*.*)

The OSL file has been generated and is attached to this email.

Can you please upload the artifacts and the OSL file to the Greenplum Tanzu Network Release for our product, PXF?
The OSL file should appear as "Open Source Licenses for PXF ${version}".

Thank you,
PXF Team (pvtl-gp-ud@vmware.com)

Generated by: ${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}
Build Job Link: ${ATC_EXTERNAL_URL}/teams/main/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}
EOF
